### ISSUE TITLE
Conversão de arquivos texto para Markdown

### ISSUE THREAD

**Issue by guidefreitas** [aneliseestevam/links#1]
Curti bastante a sua coleção de links, excelente fonte de informação para quem quer se aprofundar em desenvolvimento.

**Sugestão**
Seria legal converter os arquivos texto (.txt) para markdown (.md) para facilitar o acesso, visualização e navegação dentro do github :)

[Sugestão de leitura: Markdown Guide](https://www.markdownguide.org/basic-syntax#link-best-practices)

**Comment by aneliseestevam** [comment]
Depois de algum tempo com esse repositório parado, fiz essa alteração! Obrigada pelo incentivo, @guidefreitas.
